/**
 * 前端品牌常量。
 *
 * 值由 tools/rebrand.sh 从仓库根目录的 brand.conf 生成到下方常量。
 * 也可在构建时用 VITE_BRAND_NAME / VITE_BRAND_TAGLINE 环境变量覆盖。
 *
 * 下面的兜底字面值由 tools/rebrand.sh 生成，不要手动改。
 *
 * 注意区分两个东西：
 *   - BRAND_NAME  是「这个 fork 叫什么」，编译进产物，改它要重新构建。
 *   - appStore.siteName 是「这个部署实例叫什么」，管理员可在后台随时改，
 *     运行时生效。UI 里显示站点名请优先用 appStore.siteName，
 *     BRAND_NAME 只作为它取不到值时的兜底。
 */

const env = import.meta.env as unknown as Record<string, string | undefined>

// BEGIN GENERATED BY tools/rebrand.sh -- DO NOT EDIT BY HAND
const FALLBACK_NAME = 'Slothwatching'
const FALLBACK_TAGLINE = 'AI API Gateway'
// END GENERATED

export const BRAND_NAME: string = env.VITE_BRAND_NAME || FALLBACK_NAME
export const BRAND_TAGLINE: string = env.VITE_BRAND_TAGLINE || FALLBACK_TAGLINE
export const BRAND_PAGE_TITLE: string = `${BRAND_NAME} - ${BRAND_TAGLINE}`
