// Package branding centralises the fork's product name.
//
// 它是一个零依赖的叶子包，作用是把散落在各处的品牌字面值收敛到一处，
// 并且支持运行时覆盖 —— 改品牌名不必重新编译。
//
// 优先级：环境变量 > 编译期默认值。
// 编译期默认值由 tools/rebrand.sh 从仓库根目录的 brand.conf 生成，
// 下面两行常量是脚本的改写目标，不要手动改（改了下次跑脚本会被覆盖）。
package branding

import (
	"os"
	"strings"
)

// BEGIN GENERATED BY tools/rebrand.sh -- DO NOT EDIT BY HAND
const (
	defaultName    = "Slothwatching"
	defaultTagline = "AI API Gateway"
)

// END GENERATED

func envOr(key, fallback string) string {
	if v := strings.TrimSpace(os.Getenv(key)); v != "" {
		return v
	}
	return fallback
}

// Name 返回产品名。可用环境变量 BRAND_NAME 在运行时覆盖。
//
// 注意：绝大多数用户可见的站点名走的是数据库里的 site_name 设置
// （后台「系统设置 → 站点名称」），本函数只是它的兜底默认值 ——
// 也就是数据库还没初始化、或管理员把该设置留空时显示的名字。
func Name() string { return envOr("BRAND_NAME", defaultName) }

// Tagline 返回副标题，用于 HTML <title>。可用 BRAND_TAGLINE 覆盖。
func Tagline() string { return envOr("BRAND_TAGLINE", defaultTagline) }

// PageTitle 返回 "<Name> - <Tagline>"，供 internal/web 注入 <title> 使用。
func PageTitle() string { return Name() + " - " + Tagline() }
